version: '2.1'

jobs:
    composer:
        docker:
            # phpunit requires PHP ^7.2 and ocramius/package-versions PHP ^7.3 so we can't use PHP 7.1 as required in composer.json
            - image: circleci/php:7.3
        working_directory: ~/php-typed-array
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
            - run: composer install --classmap-authoritative
            - save_cache:
                  key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
                  paths:
                      - ./vendor
            - persist_to_workspace:
                  root: .
                  paths:
                      - vendor
    phpcs:
        docker:
            - image: steevanb/php-code-sniffs:2.0.10
              environment:
                  PHPCS_BOOTSTRAP: /var/phpcs/.circleci/phpcs/bootstrap.php
                  PHPCS_PARAMETERS: --warning-severity=0 --ignore=/vendor/
        working_directory: /var/phpcs
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run:
                name: phpcs
                command: /var/entrypoint.sh
    phpunit:
        docker:
            # phpunit requires PHP ^7.2 so we can't use PHP 7.1 as required in composer.json
            - image: php:7.2-fpm-alpine3.10
        working_directory: /var/php-typed-array
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run:
                  name: phpunit
                  command: ./bin/phpunit

    phpstan:
        docker:
            - image: php:7.1-fpm-alpine3.10
        working_directory: /var/php-typed-array
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run:
                  name: phpstan
                  command: ./bin/phpstan

    phpcf:
        docker:
            - image: steevanb/php-code-fixer:2.0.19
        working_directory: /var/php-typed-array
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run:
                  name: phpcf
                  command: ./bin/phpcf

workflows:
    version: '2.1'
    build:
        jobs:
            - composer
            - phpcf
            - phpcs:
                  requires:
                      - composer
            - phpstan:
                  requires:
                      - composer
            - phpunit:
                  requires:
                      - composer
