version: '2.1'

jobs:
    composer:
        docker:
            - image: composer:2.0.4
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
            - run: composer install --ansi
            - save_cache:
                key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
                paths:
                    - ./vendor
    phpcs:
        docker:
            - image: steevanb/php-code-sniffs:4.0.3
        working_directory: /app
        steps:
            - checkout
            - run:
                name: phpcs
                command: bin/phpcs
    phpunit:
        docker:
            # phpunit requires PHP ^7.2 so we can't use PHP 7.1 as required in composer.json
            - image: php:7.2.34-cli-alpine3.12
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
            - run:
                name: phpunit
                command: bin/phpunit

    phpstan:
        docker:
            - image: php:7.4.11-cli-buster
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
            - run:
                name: phpstan
                command: bin/phpstan

    phpcf:
        docker:
            - image: steevanb/php-code-fixer:2.0.23
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
            - run:
                name: phpcf
                command: bin/phpcf

    composerRequireChecker:
        docker:
            - image: steevanb/composer-require-checker:2.1.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
            - run:
                name: composerRequireChecker
                command: bin/composerRequireChecker

workflows:
    version: '2.1'
    CI:
        jobs:
            - composer
            - phpcf
            - phpcs
            - composerRequireChecker:
                requires:
                - composer
            - phpstan:
                requires:
                    - composer
            - phpunit:
                requires:
                    - composer
