version: '2.1'

jobs:
    composer:
        docker:
            - image: composer:1.10.20
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                key: vendor-{{ checksum "composer.json" }}
            - run: composer update --ansi
            - save_cache:
                key: vendor-{{ checksum "composer.json" }}
                paths:
                    - ./vendor
    phpcs:
        docker:
            - image: steevanb/php-code-sniffs:4.0.3
        working_directory: /app
        steps:
            - checkout
            - run:
                name: phpcs
                command: bin/phpcs
    phpunit71:
        docker:
            - image: php:7.1.33-cli-buster
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}
            - run:
                name: phpunit
                command: bin/phpunit71

    phpunit72:
        docker:
            - image: php:7.2.34-cli-buster
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}
            - run:
                  name: phpunit
                  command: bin/phpunit72

    phpunit73:
        docker:
            - image: php:7.3.26-cli-buster
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}
            - run:
                  name: phpunit
                  command: bin/phpunit73

    phpunit74:
        docker:
            - image: php:7.4.13-cli-buster
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}
            - run:
                  name: phpunit
                  command: bin/phpunit74

    phpunitBridgeSymfony44:
        docker:
            - image: steevanb/php-typed-array-ci:1.0.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}
            - run:
                  name: phpunitBridgeSymfony44
                  command: bin/phpunitBridgeSymfony44

    phpunitBridgeSymfony50:
        docker:
            - image: steevanb/php-typed-array-ci:1.0.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}
            - run:
                  name: phpunitBridgeSymfony50
                  command: bin/phpunitBridgeSymfony50

    phpunitBridgeSymfony51:
        docker:
            - image: steevanb/php-typed-array-ci:1.0.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}
            - run:
                  name: phpunitBridgeSymfony51
                  command: bin/phpunitBridgeSymfony51

    phpunitBridgeSymfony52:
        docker:
            - image: steevanb/php-typed-array-ci:1.0.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}
            - run:
                  name: phpunitBridgeSymfony52
                  command: bin/phpunitBridgeSymfony52

    phpstan:
        docker:
            - image: steevanb/php-typed-array-ci:1.0.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}
            - run:
                name: phpstan
                command: bin/phpstan

    phpcf:
        docker:
            - image: steevanb/php-code-fixer:2.0.23
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                key: vendor-{{ checksum "composer.json" }}
            - run:
                name: phpcf
                command: bin/phpcf

    composerRequireChecker:
        docker:
            - image: steevanb/composer-require-checker:2.1.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                key: vendor-{{ checksum "composer.json" }}
            - run:
                name: composerRequireChecker
                command: bin/composerRequireChecker

workflows:
    CI:
        jobs:
            - composer
            - phpcf
            - phpcs
            - composerRequireChecker:
                requires:
                    - composer
            - phpstan:
                requires:
                    - composer
            - phpunit71:
                requires:
                    - composer
            - phpunit72:
                requires:
                    - composer
            - phpunit73:
                requires:
                    - composer
            - phpunit74:
                requires:
                    - composer
            - phpunitBridgeSymfony44:
                requires:
                    - composer
            - phpunitBridgeSymfony50:
                requires:
                    - composer
            - phpunitBridgeSymfony51:
                requires:
                    - composer
            - phpunitBridgeSymfony52:
                requires:
                    - composer
