version: '2.1'

jobs:
    composer:
        docker:
            - image: composer:1.10.22
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                key: vendor-{{ checksum "composer.json" }}-3
            - run: composer update --ansi
            - save_cache:
                key: vendor-{{ checksum "composer.json" }}-3
                paths:
                    - ./vendor
    phpcs:
        docker:
            - image: steevanb/php-code-sniffs:4.1.0
        working_directory: /app
        steps:
            - checkout
            - run:
                name: phpcs
                command: bin/ci/phpcs
    phpunitPhp71:
        docker:
            - image: php:7.1.33-cli-buster
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-3
            - run:
                name: phpunit
                command: bin/ci/phpunitPhp71

    phpunitPhp72:
        docker:
            - image: php:7.2.34-cli-buster
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-3
            - run:
                  name: phpunit
                  command: bin/ci/phpunitPhp72

    phpunitPhp73:
        docker:
            - image: php:7.3.28-cli-buster
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-3
            - run:
                  name: phpunit
                  command: bin/ci/phpunitPhp73

    phpunitPhp74:
        docker:
            - image: php:7.4.19-cli-buster
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-3
            - run:
                  name: phpunit
                  command: bin/ci/phpunitPhp74

    phpunitPhp80:
        docker:
            - image: php:8.0.6-cli-buster
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-3
            - run:
                  name: phpunit
                  command: bin/ci/phpunitPhp80

    phpunitBridgeSymfony44:
        docker:
            - image: steevanb/php-typed-array-ci:1.1.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-3
            - run:
                  name: phpunitBridgeSymfony44
                  command: bin/ci/phpunitBridgeSymfony44

    phpunitBridgeSymfony50:
        docker:
            - image: steevanb/php-typed-array-ci:1.1.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-3
            - run:
                  name: phpunitBridgeSymfony50
                  command: bin/ci/phpunitBridgeSymfony50

    phpunitBridgeSymfony51:
        docker:
            - image: steevanb/php-typed-array-ci:1.1.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-3
            - run:
                  name: phpunitBridgeSymfony51
                  command: bin/ci/phpunitBridgeSymfony51

    phpunitBridgeSymfony52:
        docker:
            - image: steevanb/php-typed-array-ci:1.1.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-3
            - run:
                  name: phpunitBridgeSymfony52
                  command: bin/ci/phpunitBridgeSymfony52

    phpunitBridgeSymfony53:
        docker:
            - image: steevanb/php-typed-array-ci:1.1.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-3
            - run:
                  name: phpunitBridgeSymfony53
                  command: bin/ci/phpunitBridgeSymfony53

    phpstan:
        docker:
            - image: steevanb/php-typed-array-ci:1.1.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-3
            - run:
                name: phpstan
                command: bin/ci/phpstan

    phpcf:
        docker:
            - image: steevanb/php-code-fixer:2.0.23
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                key: vendor-{{ checksum "composer.json" }}-3
            - run:
                name: phpcf
                command: bin/ci/phpcf

    composerRequireChecker:
        docker:
            - image: steevanb/composer-require-checker:2.1.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                key: vendor-{{ checksum "composer.json" }}-3
            - run:
                name: composerRequireChecker
                command: bin/ci/composerRequireChecker

workflows:
    CI:
        jobs:
            - composer
            - phpcf
            - phpcs
            - composerRequireChecker:
                requires:
                    - composer
            - phpstan:
                requires:
                    - composer
            - phpunitPhp71:
                requires:
                    - composer
            - phpunitPhp72:
                requires:
                    - composer
            - phpunitPhp73:
                requires:
                    - composer
            - phpunitPhp74:
                requires:
                    - composer
            - phpunitPhp80:
                  requires:
                      - composer
            - phpunitBridgeSymfony44:
                requires:
                    - composer
            - phpunitBridgeSymfony50:
                requires:
                    - composer
            - phpunitBridgeSymfony51:
                requires:
                    - composer
            - phpunitBridgeSymfony52:
                requires:
                    - composer
            - phpunitBridgeSymfony53:
                  requires:
                      - composer
