name: CI
on: [push]
jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/phpcs

    phpstan:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [--php=8.1, --php=8.2, --php=8.3]
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/ci-env
            - run: bin/ci/phpstan ${{ matrix.php }}

    phpdd:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/ci-env
            - run: bin/ci/phpdd

    composer-require-checker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/ci-env
            - run: bin/ci/composer-require-checker

    composer-validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/composer-validate

    shellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/shellcheck

    unused-scanner:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/unused-scanner

    phpunit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [--php=8.1, --php=8.2, --php=8.3]
                symfony: [--symfony=6.1, --symfony=6.2, --symfony=6.3, --symfony=6.4]
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/ci-env
            - run: bin/ci/phpunit ${{ matrix.php }} ${{ matrix.symfony }}
