name: CI
on: [push]
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout repository
                uses: actions/checkout@v4
            -
                name: Composer cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/ci/env
            - run: bin/ci/validate --theme=summary
